# Generated by Django 5.0.4 on 2024-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга (локализованный этап)', 'verbose_name_plural': 'Услуги (локализованные этапы)'},
        ),
        migrations.AlterModelOptions(
            name='service_type',
            options={'verbose_name': 'Направление услуги', 'verbose_name_plural': 'Направления услуг'},
        ),
        migrations.AlterField(
            model_name='service',
            name='payment_made',
            field=models.IntegerField(db_default=0, verbose_name='Сумма частичной оплаты счета'),
        ),
    ]
