# Generated by Django 5.0.4 on 2024-05-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_alter_service_options_alter_service_type_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='web_site',
            field=models.CharField(default='site.ru', max_length=250, verbose_name='Веб сайт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='kpp',
            field=models.IntegerField(default='111111111', verbose_name='КПП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='management_full_name',
            field=models.CharField(default='Фамилия Имя Отчество', max_length=250, verbose_name='Управляющее лицо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='management_post',
            field=models.CharField(default='Генеральный директор', max_length=250, verbose_name='Должность управляющего лица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(default='ООО Короткое имя', max_length=250, verbose_name='Краткое наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='ur_adres',
            field=models.TextField(default='Юр. адрес', verbose_name='Юридический адрес'),
            preserve_default=False,
        ),
    ]
